// GENERATED by scripts/build-all.mjs — do not edit by hand.
// Committed placeholder (empty) so `vite dev` and `tsc` work before a build.
import type { PixelGrid } from '../../src/pixel';

export interface HubGame {
  name: string;
  title: string;
  description: string;
  tags: string[];
  href: string;
  thumb: PixelGrid | null;
}

export const GAMES: HubGame[] = [];
