import Phaser from 'phaser';
import { SceneKeys, AudioKeys } from '../types/keys';
import { GAME_WIDTH, GAME_HEIGHT } from '../config';
import { bakeArt } from '../art';
import { HEROES, HERO_IDS } from '../types/roster';

export class PreloadScene extends Phaser.Scene {
  constructor() {
    super(SceneKeys.Preload);
  }

  preload(): void {
    this.drawProgressBar();
    for (const key of Object.values(AudioKeys)) {
      // Load BOTH formats — iOS/Safari can't decode OGG/Vorbis, so it falls back
      // to the MP3. Phaser picks the first the browser supports.
      this.load.audio(key, [`audio/${key}.ogg`, `audio/${key}.mp3`]);
    }
    // the 21 hero sprites, pixel-art versions (true low-res grid, crisp under
    // pixelArt:true). Generated by scripts/pixelate.mjs from the originals in
    // public/heroes/ — see public/heroes-pixel/. PNG name == hero id.
    for (const id of HERO_IDS) {
      this.load.image(HEROES[id].tex, `heroes-pixel/${id}.png`);
    }
  }

  create(): void {
    bakeArt(this);
    this.scene.start(SceneKeys.Menu);
  }

  private drawProgressBar(): void {
    const barW = GAME_WIDTH * 0.6;
    const barH = 12;
    const x = (GAME_WIDTH - barW) / 2;
    const y = GAME_HEIGHT / 2;
    const frame = this.add.graphics();
    frame.lineStyle(1, 0xffffff, 0.5).strokeRect(x, y, barW, barH);
    const bar = this.add.graphics();
    this.load.on(Phaser.Loader.Events.PROGRESS, (p: number) => {
      bar.clear();
      bar.fillStyle(0xffffff, 1).fillRect(x + 1, y + 1, (barW - 2) * p, barH - 2);
    });
    this.load.once(Phaser.Loader.Events.COMPLETE, () => {
      bar.destroy();
      frame.destroy();
    });
  }
}
