import Phaser from 'phaser';
import { SceneKeys, AudioKeys, MusicKeys, TextureKeys } from '../types/keys';
import { GAME_WIDTH, GAME_HEIGHT } from '../config';
import { bakeArt } from '../art';
import { HEROES, HERO_IDS } from '../types/roster';

export class PreloadScene extends Phaser.Scene {
  constructor() {
    super(SceneKeys.Preload);
  }

  preload(): void {
    this.drawProgressBar();
    // Original SFX ship ogg+mp3 (Phaser picks the first the browser supports; iOS
    // can't decode ogg so it uses the mp3). The zombie SFX + music are mp3-only —
    // mp3 decodes everywhere including iOS, so a single source is fine.
    const dualFormat = new Set<string>([AudioKeys.Shoot, AudioKeys.Hit, AudioKeys.Explode, AudioKeys.Place, AudioKeys.Lose, AudioKeys.Click]);
    for (const key of Object.values(AudioKeys)) {
      this.load.audio(key, dualFormat.has(key) ? [`audio/${key}.ogg`, `audio/${key}.mp3`] : [`audio/${key}.mp3`]);
    }
    for (const key of Object.values(MusicKeys)) {
      this.load.audio(key, [`audio/${key}.mp3`]);
    }
    // the 21 hero sprites, pixel-art versions (true low-res grid, crisp under
    // pixelArt:true). Generated by scripts/pixelate.mjs from the originals in
    // public/heroes/ — see public/heroes-pixel/. PNG name == hero id.
    for (const id of HERO_IDS) {
      this.load.image(HEROES[id].tex, `heroes-pixel/${id}.png`);
    }

    // Map tiles + decor — real art cut from the user's asset sheet (public/tiles/).
    const T = TextureKeys;
    const tileFiles: Array<[string, string]> = [
      [T.Grass, 'grass'], [T.Path, 'dirt'], [T.GrassFringe, 'grass_fringe'],
      [T.RoadStraight, 'road_straight'], [T.RoadCorner, 'road_corner'],
      [T.Grass0, 'grass0'], [T.Grass1, 'grass1'], [T.Grass2, 'grass2'], [T.Grass3, 'grass3'], [T.Grass4, 'grass4'],
      [T.Pad, 'pad_blue'], [T.PadOn, 'pad_green'],
      [T.TreeRound, 'tree_round'], [T.TreePine, 'tree_pine'], [T.TreeBig, 'tree_big'],
      [T.TreeSmall1, 'tree_small1'], [T.TreeSmall2, 'tree_small2'],
      [T.RockBig1, 'rock_big1'], [T.RockBig2, 'rock_big2'], [T.RockMed1, 'rock_med1'], [T.RockMed2, 'rock_med2'],
      [T.Bush, 'bush'], [T.Flowers, 'flowers'], [T.Log, 'log'], [T.Mushroom, 'mushroom'],
    ];
    for (const [key, file] of tileFiles) this.load.image(key, `tiles/${file}.png`);

    // animated zombie spritesheets (cut by scripts/cut-zombie-sheet.mjs). Each
    // "sheet set" has a tall STAND png + a wide LIE png; cell sizes differ per set.
    const SS = TextureKeys;
    this.load.spritesheet(SS.ZombieGirlStand, 'enemies/zombie-girl-stand.png', { frameWidth: 118, frameHeight: 141 });
    this.load.spritesheet(SS.ZombieGirlLie, 'enemies/zombie-girl-lie.png', { frameWidth: 158, frameHeight: 142 });
    this.load.spritesheet(SS.ZombieBossStand, 'enemies/zombie-boss-stand.png', { frameWidth: 117, frameHeight: 141 });
    this.load.spritesheet(SS.ZombieBossLie, 'enemies/zombie-boss-lie.png', { frameWidth: 157, frameHeight: 142 });
    this.load.spritesheet(SS.ZombieSpeedStand, 'enemies/zombie-speed-stand.png', { frameWidth: 130, frameHeight: 182 });
    this.load.spritesheet(SS.ZombieSpeedLie, 'enemies/zombie-speed-lie.png', { frameWidth: 179, frameHeight: 98 });
    this.load.spritesheet(SS.ZombieBruteStand, 'enemies/zombie-brute-stand.png', { frameWidth: 118, frameHeight: 141 });
    this.load.spritesheet(SS.ZombieBruteLie, 'enemies/zombie-brute-lie.png', { frameWidth: 158, frameHeight: 142 });
    // per-map bosses (cut by cut-zombie-sheet.mjs khoai|hakj)
    this.load.spritesheet(SS.ZombieKhoaiStand, 'enemies/zombie-khoai-stand.png', { frameWidth: 242, frameHeight: 193 });
    this.load.spritesheet(SS.ZombieKhoaiLie, 'enemies/zombie-khoai-lie.png', { frameWidth: 242, frameHeight: 228 });
    this.load.spritesheet(SS.ZombieHakjStand, 'enemies/zombie-hakj-stand.png', { frameWidth: 258, frameHeight: 232 });
    this.load.spritesheet(SS.ZombieHakjLie, 'enemies/zombie-hakj-lie.png', { frameWidth: 258, frameHeight: 223 });

    // animated FX (cut from the user's effect sheets by scripts/cut-effect-sheet.mjs)
    this.load.spritesheet(SS.FxFireball, 'effects/fireball.png', { frameWidth: 64, frameHeight: 64 });
    this.load.spritesheet(SS.FxSlash, 'effects/slash.png', { frameWidth: 80, frameHeight: 80 });
  }

  create(): void {
    bakeArt(this);
    this.createZombieAnims();
    this.createFxAnims();
    // Wait for the Bangers display font (titles + banners) so the first text that
    // renders already uses it instead of flashing the monospace fallback.
    const go = () => this.scene.start(SceneKeys.Menu);
    const fonts = (document as unknown as { fonts?: { load: (f: string) => Promise<unknown>; ready: Promise<unknown> } }).fonts;
    if (fonts) {
      // load both display fonts (Bangers for banners, Creepster for boss titles)
      const load = Promise.all([
        fonts.load('400 32px Bangers').catch(() => {}),
        fonts.load('400 32px Creepster').catch(() => {}),
      ]);
      Promise.race([load, new Promise((r) => setTimeout(r, 1500))]).then(go);
    } else {
      go();
    }
  }

  // Define animations for every zombie sheet set. Anim keys are `<sheet>-<name>`
  // (e.g. girl-walk, boss-walk, speed-walk) so Zombie can pick by its def.sheet.
  // Frame index = row*cols + col, where cols = the widest row of that sheet.
  private createZombieAnims(): void {
    const mk = (
      key: string, sheet: string, row: number, cols: number, n: number,
      frameRate: number, repeat: number, yoyo = false,
    ) => {
      if (this.anims.exists(key)) return;
      this.anims.create({
        key,
        frames: Array.from({ length: n }, (_, i) => ({ key: sheet, frame: row * cols + i })),
        frameRate, repeat, yoyo,
      });
    };

    // girl + boss share the same layout (stand 6 cols / lie 5 cols).
    for (const [pfx, stand, lie] of [
      ['girl', TextureKeys.ZombieGirlStand, TextureKeys.ZombieGirlLie],
      ['boss', TextureKeys.ZombieBossStand, TextureKeys.ZombieBossLie],
      ['brute', TextureKeys.ZombieBruteStand, TextureKeys.ZombieBruteLie],
    ] as const) {
      mk(`${pfx}-idle`, stand, 0, 6, 4, 4, -1, true);
      mk(`${pfx}-walk`, stand, 1, 6, 6, 9, -1);
      mk(`${pfx}-attackA`, stand, 2, 6, 5, 12, 0);
      mk(`${pfx}-attackB`, stand, 3, 6, 6, 12, 0);
      mk(`${pfx}-takeDamage`, stand, 4, 6, 3, 14, 0);
      mk(`${pfx}-victory`, stand, 5, 6, 4, 6, -1);
      mk(`${pfx}-death`, lie, 0, 5, 3, 8, 0);
      mk(`${pfx}-rise`, lie, 1, 5, 5, 9, 0);
    }

    // speed (bucket-head): stand 6 cols, rows idle/walk/attack/takeDamage/victory;
    // lie sheet has a single death row (4 cols). No attackB/rise — alias to attack.
    const sp = TextureKeys.ZombieSpeedStand;
    mk('speed-idle', sp, 0, 6, 4, 4, -1, true);
    mk('speed-walk', sp, 1, 6, 6, 9, -1);
    mk('speed-attackA', sp, 2, 6, 5, 12, 0);
    mk('speed-attackB', sp, 2, 6, 5, 12, 0); // reuse attack as B
    mk('speed-takeDamage', sp, 3, 6, 3, 14, 0);
    mk('speed-victory', sp, 4, 6, 3, 6, -1);
    mk('speed-death', TextureKeys.ZombieSpeedLie, 0, 4, 4, 8, 0);
    mk('speed-rise', TextureKeys.ZombieSpeedLie, 0, 4, 4, 8, 0); // no rise art → reuse death

    // khoai (Normal boss): stand 6 cols × 6 rows; lie 3 cols × 2 rows.
    const kh = TextureKeys.ZombieKhoaiStand, khL = TextureKeys.ZombieKhoaiLie;
    mk('khoai-idle', kh, 0, 6, 4, 4, -1, true);
    mk('khoai-walk', kh, 1, 6, 6, 9, -1);
    mk('khoai-attackA', kh, 2, 6, 4, 11, 0);
    mk('khoai-attackB', kh, 3, 6, 4, 11, 0);
    mk('khoai-takeDamage', kh, 4, 6, 2, 14, 0);
    mk('khoai-victory', kh, 5, 6, 4, 6, -1);
    mk('khoai-death', khL, 0, 3, 3, 8, 0);
    mk('khoai-rise', khL, 1, 3, 3, 9, 0);

    // hakj (Hard boss): stand 3 cols × 6 rows; lie 3 cols × 2 rows.
    const hj = TextureKeys.ZombieHakjStand, hjL = TextureKeys.ZombieHakjLie;
    mk('hakj-idle', hj, 0, 3, 3, 4, -1, true);
    mk('hakj-walk', hj, 1, 3, 3, 8, -1);
    mk('hakj-attackA', hj, 2, 3, 3, 11, 0);
    mk('hakj-attackB', hj, 3, 3, 3, 11, 0);
    mk('hakj-takeDamage', hj, 4, 3, 2, 14, 0);
    mk('hakj-victory', hj, 5, 3, 3, 6, -1);
    mk('hakj-death', hjL, 0, 3, 3, 8, 0);
    mk('hakj-rise', hjL, 1, 3, 3, 9, 0);
  }

  // One-shot FX animations (play once, then the sprite is destroyed by the scene).
  private createFxAnims(): void {
    if (!this.anims.exists('fx-fireball')) {
      this.anims.create({
        key: 'fx-fireball',
        frames: this.anims.generateFrameNumbers(TextureKeys.FxFireball, { start: 0, end: 6 }),
        frameRate: 22, repeat: 0,
      });
    }
    if (!this.anims.exists('fx-slash')) {
      this.anims.create({
        key: 'fx-slash',
        frames: this.anims.generateFrameNumbers(TextureKeys.FxSlash, { start: 0, end: 5 }),
        frameRate: 30, repeat: 0,
      });
    }
  }

  private drawProgressBar(): void {
    const barW = GAME_WIDTH * 0.6;
    const barH = 12;
    const x = (GAME_WIDTH - barW) / 2;
    const y = GAME_HEIGHT / 2;
    const frame = this.add.graphics();
    frame.lineStyle(1, 0xffffff, 0.5).strokeRect(x, y, barW, barH);
    const bar = this.add.graphics();
    this.load.on(Phaser.Loader.Events.PROGRESS, (p: number) => {
      bar.clear();
      bar.fillStyle(0xffffff, 1).fillRect(x + 1, y + 1, (barW - 2) * p, barH - 2);
    });
    this.load.once(Phaser.Loader.Events.COMPLETE, () => {
      bar.destroy();
      frame.destroy();
    });
  }
}
