import Phaser from 'phaser';
import { bakeSprite, type PixelGrid } from '../../../src/pixel';
import { TextureKeys } from './types/keys';

// Pixel-art (Sweetie-16, 24x24) generated from a verified design grid (see
// pixel-art skill: previewed + Playwright-verified before baking). Procedural
// shapes (octagon bases, turrets, top-down tanks, tiles, FX).

type Art = Record<string, PixelGrid>;

const ART: Art = {
  baseGun: {
    map: {".":null,"p":"#566c86","r":"#94b0c2","b":"#333c57","k":"#1a1c2c"},
    grid: [
      "........................",
      "........................",
      "............k...........",
      "........kkkkrkkkk.......",
      ".......krrrrrrrrrk......",
      "......krrppppppprrk.....",
      ".....kbrppppppppprbk....",
      "....krrppppppppppprrk...",
      "...krrppppppppppppprrk..",
      "...krppppppppppppppprk..",
      "...krppppppppppppppprk..",
      "...krppppppppppppppprk..",
      "..krrppppppppppppppprrk.",
      "...krppppppppppppppprk..",
      "...krppppppppppppppprk..",
      "...krppppppppppppppprk..",
      "...krrppppppppppppprrk..",
      "....krrppppppppppprrk...",
      ".....kbrppppppppprbk....",
      "......krrppppppprrk.....",
      ".......krrrrrrrrrk......",
      "........kkkkrkkkk.......",
      "............k...........",
      "........................",
    ],
  },
  baseCannon: {
    map: {".":null,"p":"#257179","r":"#73eff7","b":"#333c57","k":"#1a1c2c"},
    grid: [
      "........................",
      "........................",
      "............k...........",
      "........kkkkrkkkk.......",
      ".......krrrrrrrrrk......",
      "......krrppppppprrk.....",
      ".....kbrppppppppprbk....",
      "....krrppppppppppprrk...",
      "...krrppppppppppppprrk..",
      "...krppppppppppppppprk..",
      "...krppppppppppppppprk..",
      "...krppppppppppppppprk..",
      "..krrppppppppppppppprrk.",
      "...krppppppppppppppprk..",
      "...krppppppppppppppprk..",
      "...krppppppppppppppprk..",
      "...krrppppppppppppprrk..",
      "....krrppppppppppprrk...",
      ".....kbrppppppppprbk....",
      "......krrppppppprrk.....",
      ".......krrrrrrrrrk......",
      "........kkkkrkkkk.......",
      "............k...........",
      "........................",
    ],
  },
  baseMissile: {
    map: {".":null,"p":"#29366f","r":"#3b5dc9","b":"#333c57","k":"#1a1c2c"},
    grid: [
      "........................",
      "........................",
      "............k...........",
      "........kkkkrkkkk.......",
      ".......krrrrrrrrrk......",
      "......krrppppppprrk.....",
      ".....kbrppppppppprbk....",
      "....krrppppppppppprrk...",
      "...krrppppppppppppprrk..",
      "...krppppppppppppppprk..",
      "...krppppppppppppppprk..",
      "...krppppppppppppppprk..",
      "..krrppppppppppppppprrk.",
      "...krppppppppppppppprk..",
      "...krppppppppppppppprk..",
      "...krppppppppppppppprk..",
      "...krrppppppppppppprrk..",
      "....krrppppppppppprrk...",
      ".....kbrppppppppprbk....",
      "......krrppppppprrk.....",
      ".......krrrrrrrrrk......",
      "........kkkkrkkkk.......",
      "............k...........",
      "........................",
    ],
  },
  turretGun: {
    map: {".":null,"h":"#94b0c2","b":"#566c86","m":"#333c57","k":"#1a1c2c"},
    grid: [
      "...........kk...........",
      "..........kmmk..........",
      "..........kbbk..........",
      "..........kbbk..........",
      "..........kbbk..........",
      "..........kbbk..........",
      "..........kbbk..........",
      "..........kbbk..........",
      ".........kkbbkkk........",
      "........khhbbhhhk.......",
      ".......khhhbbhhhhk......",
      ".......khhhbbhhhhk......",
      ".......khhhbbhhhhk......",
      "......khhhhhhhhhhhk.....",
      ".......khhhhhhhhhk......",
      ".......khhhhhhhhhk......",
      ".......khhhhhhhhhk......",
      "........khhhhhhhk.......",
      ".........kkkhkkk........",
      "............k...........",
      "........................",
      "........................",
      "........................",
      "........................",
    ],
  },
  turretCannon: {
    map: {".":null,"h":"#73eff7","b":"#257179","m":"#333c57","k":"#1a1c2c"},
    grid: [
      "........................",
      ".........kkkkkk.........",
      "........kmmmmmmk........",
      "........kmmmmmmk........",
      ".........kbbbbk.........",
      ".........kbbbbk.........",
      ".........kbbbbk.........",
      ".........kbbbbkk........",
      "........khbbbbhhk.......",
      ".......khhbbbbhhhk......",
      "......khhhbbbbhhhhk.....",
      "......khhhbbbbhhhhk.....",
      "......khhhbbbbhhhhk.....",
      ".....khhhhbbbbhhhhhk....",
      "......khhhhhhhhhhhk.....",
      "......khhhhhhhhhhhk.....",
      "......khhhhhhhhhhhk.....",
      ".......khhhhhhhhhk......",
      "........khhhhhhhk.......",
      ".........kkkhkkk........",
      "............k...........",
      "........................",
      "........................",
      "........................",
    ],
  },
  turretMissile: {
    map: {".":null,"h":"#3b5dc9","b":"#29366f","m":"#b13e53","k":"#1a1c2c"},
    grid: [
      "........................",
      "........kkk..kkk........",
      ".......kmmmkkmmmk.......",
      ".......kbbbkkbbbk.......",
      ".......kbbbkkbbbk.......",
      ".......kbbbkkbbbk.......",
      ".......kbbbkkbbbk.......",
      ".......kbbbkkbbbk.......",
      ".......kbbbkhbbbk.......",
      ".......kbbbhhbbbk.......",
      ".......kbbbhhbbbhk......",
      ".......kbbbhhbbbhk......",
      ".......kbbbhhbbbhk......",
      "......khbbbhhbbbhhk.....",
      ".......khhhhhhhhhk......",
      ".......khhhhhhhhhk......",
      ".......khhhhhhhhhk......",
      "........khhhhhhhk.......",
      ".........kkkhkkk........",
      "............k...........",
      "........................",
      "........................",
      "........................",
      "........................",
    ],
  },
  enemyLight: {
    map: {".":null,"t":"#333c57","d":"#1a1c2c","c":"#38b764","u":"#a7f070","g":"#566c86","k":"#1a1c2c"},
    grid: [
      "........................",
      "...........kk...........",
      "....kkkk..kggk..kkkk....",
      "...kttttk.kggk.kttttk...",
      "...ktddtkkkggkkktddtk...",
      "...kttttcccggcccttttk...",
      "...kttttcccggcccttttk...",
      "...ktddtcccggccctddtk...",
      "...kttttcccggcccttttk...",
      "...kttttccugguucttttk...",
      "...ktddtcuugguuutddtk...",
      "...kttttcuugguuuttttk...",
      "...kttttuuuuuuuuutttk...",
      "...ktddtcuuuuuuutddtk...",
      "...kttttcuuuuuuuttttk...",
      "...kttttccuuuuucttttk...",
      "...ktddtccccuccctddtk...",
      "...kttttccccccccttttk...",
      "...kttttccccccccttttk...",
      "...ktddtkkkkkkkktddtk...",
      "...kttttk......kttttk...",
      "....kkkk........kkkk....",
      "........................",
      "........................",
    ],
  },
  enemyMedium: {
    map: {".":null,"t":"#333c57","d":"#1a1c2c","c":"#ef7d57","u":"#ffcd75","g":"#566c86","k":"#1a1c2c"},
    grid: [
      "........................",
      "...........kk...........",
      "....kkkk..kggk..kkkk....",
      "...kttttk.kggk.kttttk...",
      "...ktddtkkkggkkktddtk...",
      "...kttttcccggcccttttk...",
      "...kttttcccggcccttttk...",
      "...ktddtcccggccctddtk...",
      "...kttttcccggcccttttk...",
      "...kttttccugguucttttk...",
      "...ktddtcuugguuutddtk...",
      "...kttttcuugguuuttttk...",
      "...kttttuuuuuuuuutttk...",
      "...ktddtcuuuuuuutddtk...",
      "...kttttcuuuuuuuttttk...",
      "...kttttccuuuuucttttk...",
      "...ktddtccccuccctddtk...",
      "...kttttccccccccttttk...",
      "...kttttccccccccttttk...",
      "...ktddtkkkkkkkktddtk...",
      "...kttttk......kttttk...",
      "....kkkk........kkkk....",
      "........................",
      "........................",
    ],
  },
  enemyHeavy: {
    map: {".":null,"t":"#1a1c2c","d":"#1a1c2c","c":"#b13e53","u":"#5d275d","g":"#566c86","k":"#1a1c2c"},
    grid: [
      "........................",
      "...........kk...........",
      "....kkkk..kggk..kkkk....",
      "...kttttk.kggk.kttttk...",
      "...ktddtkkkggkkktddtk...",
      "...kttttcccggcccttttk...",
      "...kttttcccggcccttttk...",
      "...ktddtcccggccctddtk...",
      "...kttttcccggcccttttk...",
      "...kttttccugguucttttk...",
      "...ktddtcuugguuutddtk...",
      "...kttttcuugguuuttttk...",
      "...kttttuuuuuuuuutttk...",
      "...ktddtcuuuuuuutddtk...",
      "...kttttcuuuuuuuttttk...",
      "...kttttccuuuuucttttk...",
      "...ktddtccccuccctddtk...",
      "...kttttccccccccttttk...",
      "...kttttccccccccttttk...",
      "...ktddtkkkkkkkktddtk...",
      "...kttttk......kttttk...",
      "....kkkk........kkkk....",
      "........................",
      "........................",
    ],
  },
  grass: {
    map: {".":null,"g":"#38b764","d":"#a7f070"},
    grid: [
      "gggggggggggggggggggggggg",
      "gggggggggggggggggggggggg",
      "gggggggggddggggggggggggg",
      "gggggggggggggggggggggggg",
      "ggggggggggggggggggggddgg",
      "gggddggggggggggggggggggg",
      "gggggggggggggggggggggggg",
      "gggggggggggggggggggggggg",
      "gggggggggggggggddggggggg",
      "gggggggggggggggggggggggg",
      "gggggggggggggggggggggggg",
      "gggggggggggggggggggggggg",
      "ggddgggggggggggggggggggg",
      "gggggggggggggggggggggggg",
      "ggggggggggggddgggggggggg",
      "ggggggggggggggggggggggdd",
      "gggggggggggggggggggggggg",
      "gggggggggggggggggggggggg",
      "ggggggddgggggggggggggggg",
      "gggggggggggggggggggggggg",
      "ggggggggggggggggggddgggg",
      "gggggggggggggggggggggggg",
      "gggggggggggggggggggggggg",
      "gggggggggggggggggggggggg",
    ],
  },
  path: {
    map: {".":null,"p":"#333c57","d":"#566c86"},
    grid: [
      "pppppppppppppppppppppppp",
      "pppppppppppppppppppppppp",
      "pppppppppppppppppppppppp",
      "pppppppppppdpppppppppppp",
      "pppppppppppppppppppppppp",
      "pppppppppppppppppppppppp",
      "ppppdppppppppppppppppppp",
      "pppppppppppppppppppppppp",
      "pppppppppppppppppppppppp",
      "pppppppppppppppppdpppppp",
      "pppppppppppppppppppppppp",
      "pppppppppppppppppppppppp",
      "pppppppppppppppppppppppp",
      "pppppppppppppppppppppppp",
      "pppppppppppppppppppppppp",
      "pppppppppppppppppppppppp",
      "pppppppdpppppppppppppppp",
      "pppppppppppppppppppppppp",
      "pppppppppppppppppppdpppp",
      "pppppppppppppppppppppppp",
      "pppppppppppppppppppppppp",
      "pppppppppppppdpppppppppp",
      "pppppppppppppppppppppppp",
      "pppppppppppppppppppppppp",
    ],
  },
  tree: {
    map: {".":null,"t":"#333c57","f":"#38b764","l":"#a7f070","k":"#1a1c2c"},
    grid: [
      "............k...........",
      ".........kkkfkkk........",
      ".......kkfffffffkk......",
      "......kfffffffffffk.....",
      ".....kfffffflffffffk....",
      ".....kffflllllllfffk....",
      "....kffflllllllllfffk...",
      "....kffflllllllllfffk...",
      "....kffflllllllllfffk...",
      "...kffflllllllllllfffk..",
      "...kfffflllllllllffffk..",
      "...kfffflllllllllffffk..",
      "..kffffflllllllllfffffk.",
      "...kffffflllllllfffffk..",
      "...kfffffffflffffffffk..",
      "...kfffffffffffffffffk..",
      "....kfffffffffffffffk...",
      ".....kkkfkttftkkfkkk....",
      "........kkttttk.k.......",
      ".........kttttk.........",
      ".........kttttk.........",
      ".........kttttk.........",
      "..........kkkk..........",
      "........................",
    ],
  },
  barrel: {
    map: {".":null,"b":"#b13e53","r":"#333c57","k":"#1a1c2c"},
    grid: [
      "........................",
      "........................",
      "........................",
      "........................",
      "........kkkkkkkk........",
      ".......krrrrrrrrk.......",
      ".......krrrrrrrrk.......",
      ".......kbbbbbbbbk.......",
      ".......kbbbbbbbbk.......",
      ".......kbbbbbbbbk.......",
      ".......kbbbbbbbbk.......",
      ".......kbbbbbbbbk.......",
      ".......krrrrrrrrk.......",
      ".......krrrrrrrrk.......",
      ".......kbbbbbbbbk.......",
      ".......kbbbbbbbbk.......",
      ".......kbbbbbbbbk.......",
      ".......kbbbbbbbbk.......",
      ".......krrrrrrrrk.......",
      ".......krrrrrrrrk.......",
      "........kkkkkkkk........",
      "........................",
      "........................",
      "........................",
    ],
  },
  bullet: {
    map: {".":null,"y":"#ffcd75"},
    grid: [
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
      "............y...........",
      "..........yyyyy.........",
      "..........yyyyy.........",
      ".........yyyyyyy........",
      "..........yyyyy.........",
      "..........yyyyy.........",
      "............y...........",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
    ],
  },
  shell: {
    map: {".":null,"o":"#ef7d57","r":"#b13e53"},
    grid: [
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
      "............r...........",
      "..........rrrrr.........",
      ".........rrooorr........",
      ".........rooooor........",
      "........rrooooorr.......",
      ".........rooooor........",
      ".........rrooorr........",
      "..........rrrrr.........",
      "............r...........",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
    ],
  },
  missile: {
    map: {".":null,"b":"#566c86","r":"#b13e53"},
    grid: [
      "........................",
      "........................",
      "........................",
      ".........rrrrrr.........",
      ".........rrrrrr.........",
      ".........rrrrrr.........",
      "..........bbbb..........",
      "..........bbbb..........",
      "..........bbbb..........",
      "..........bbbb..........",
      "..........bbbb..........",
      "..........bbbb..........",
      "..........bbbb..........",
      "..........bbbb..........",
      "..........bbbb..........",
      "..........bbbb..........",
      "..........bbbb..........",
      "..........bbbb..........",
      "..........bbbb..........",
      "..........bbbb..........",
      "........................",
      "........................",
      "........................",
      "........................",
    ],
  },
  explosion: {
    map: {".":null,"o":"#ef7d57","y":"#ffcd75","w":"#f4f4f4"},
    grid: [
      "........................",
      "........................",
      "........................",
      "............o...........",
      "........ooooooooo.......",
      ".......ooooooooooo......",
      "......ooooooyoooooo.....",
      ".....ooooyyyyyyyoooo....",
      "....ooooyyyyyyyyyoooo...",
      "....oooyyyyywyyyyyooo...",
      "....oooyyywwwwwyyyooo...",
      "....oooyyywwwwwyyyooo...",
      "...oooyyywwwwwwwyyyooo..",
      "....oooyyywwwwwyyyooo...",
      "....oooyyywwwwwyyyooo...",
      "....oooyyyyywyyyyyooo...",
      "....ooooyyyyyyyyyoooo...",
      ".....ooooyyyyyyyoooo....",
      "......ooooooyoooooo.....",
      ".......ooooooooooo......",
      "........ooooooooo.......",
      "............o...........",
      "........................",
      "........................",
    ],
  },
  buildable: {
    map: {".":null,"h":"#a7f070"},
    grid: [
      "........................",
      "........................",
      "..hhhhhhhhhhhhhhhhhhhh..",
      "..hhhhhhhhhhhhhhhhhhhh..",
      "..hhhhhhhhhhhhhhhhhhhh..",
      "..hhhhhhhhhhhhhhhhhhhh..",
      "..hhhhhhhhhhhhhhhhhhhh..",
      "..hhhhhhhhhhhhhhhhhhhh..",
      "..hhhhhhhhhhhhhhhhhhhh..",
      "..hhhhhhhhhhhhhhhhhhhh..",
      "..hhhhhhhhhhhhhhhhhhhh..",
      "..hhhhhhhhhhhhhhhhhhhh..",
      "..hhhhhhhhhhhhhhhhhhhh..",
      "..hhhhhhhhhhhhhhhhhhhh..",
      "..hhhhhhhhhhhhhhhhhhhh..",
      "..hhhhhhhhhhhhhhhhhhhh..",
      "..hhhhhhhhhhhhhhhhhhhh..",
      "..hhhhhhhhhhhhhhhhhhhh..",
      "..hhhhhhhhhhhhhhhhhhhh..",
      "..hhhhhhhhhhhhhhhhhhhh..",
      "..hhhhhhhhhhhhhhhhhhhh..",
      "..hhhhhhhhhhhhhhhhhhhh..",
      "........................",
      "........................",
    ],
  },
};

export function bakeArt(scene: Phaser.Scene): void {
  bakeSprite(scene, TextureKeys.BaseGun, ART.baseGun, { px: 2 });
  bakeSprite(scene, TextureKeys.BaseCannon, ART.baseCannon, { px: 2 });
  bakeSprite(scene, TextureKeys.BaseMissile, ART.baseMissile, { px: 2 });
  bakeSprite(scene, TextureKeys.TurretGun, ART.turretGun, { px: 2 });
  bakeSprite(scene, TextureKeys.TurretCannon, ART.turretCannon, { px: 2 });
  bakeSprite(scene, TextureKeys.TurretMissile, ART.turretMissile, { px: 2 });
  bakeSprite(scene, TextureKeys.EnemyLight, ART.enemyLight, { px: 2 });
  bakeSprite(scene, TextureKeys.EnemyMedium, ART.enemyMedium, { px: 2 });
  bakeSprite(scene, TextureKeys.EnemyHeavy, ART.enemyHeavy, { px: 2 });
  bakeSprite(scene, TextureKeys.Grass, ART.grass, { px: 2 });
  bakeSprite(scene, TextureKeys.Path, ART.path, { px: 2 });
  bakeSprite(scene, TextureKeys.Tree, ART.tree, { px: 2 });
  bakeSprite(scene, TextureKeys.Barrel, ART.barrel, { px: 2 });
  bakeSprite(scene, TextureKeys.Bullet, ART.bullet, { px: 2 });
  bakeSprite(scene, TextureKeys.Shell, ART.shell, { px: 2 });
  bakeSprite(scene, TextureKeys.Missile, ART.missile, { px: 2 });
  bakeSprite(scene, TextureKeys.Explosion, ART.explosion, { px: 2 });
  bakeSprite(scene, TextureKeys.Buildable, ART.buildable, { px: 2 });
}
