// Build every game under games/* into dist/<game>/, generate the hub manifest,
// build the Phaser hub app into dist/ (its index.html is the landing page), and
// inject a crawlable fallback link list. Used by `npm run build:all`.
//
// Base path: GitHub Pages serves from /<repo>/, so games build with base
// "/<repo>/<game>/" and the hub with base "/<repo>/". Override the repo segment
// via BASE_PATH env (e.g. BASE_PATH=/ for root-domain / local preview).
import {
  readdirSync,
  statSync,
  existsSync,
  readFileSync,
  writeFileSync,
  copyFileSync,
} from 'node:fs';
import { join } from 'node:path';
import { execSync } from 'node:child_process';

const gamesDir = 'games';
// Leading+trailing slash; "/phaser/" by default (this repo on GitHub Pages).
const BASE = (process.env.BASE_PATH ?? '/phaser/').replace(/\/?$/, '/');

if (!existsSync(gamesDir)) {
  console.error('No games/ directory found.');
  process.exit(1);
}

const games = readdirSync(gamesDir).filter((name) => {
  const p = join(gamesDir, name);
  return statSync(p).isDirectory() && existsSync(join(p, 'vite.config.mjs'));
});

if (games.length === 0) {
  console.log('No games to build.');
  process.exit(0);
}

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function titleOf(game) {
  try {
    const file = join(gamesDir, game, 'index.html');
    if (existsSync(file)) {
      const m = readFileSync(file, 'utf8').match(/<title>([^<]*)<\/title>/i);
      if (m) return m[1].trim();
    }
  } catch {
    /* ignore */
  }
  return game;
}

// Gather display metadata + optional pixel thumb. Missing/malformed never throws.
function metaOf(game) {
  let meta = {};
  const file = join(gamesDir, game, 'game.json');
  if (existsSync(file)) {
    try {
      meta = JSON.parse(readFileSync(file, 'utf8'));
    } catch (e) {
      console.warn(`  ! ${game}/game.json invalid JSON — ignoring (${e.message})`);
    }
  }
  // Validate thumb shape: { grid:string[], map:{} }. Bad → null (use default).
  let thumb = null;
  if (meta.thumb && Array.isArray(meta.thumb.grid) && meta.thumb.map) {
    const rows = meta.thumb.grid;
    const ok =
      rows.length > 0 &&
      rows.every((r) => typeof r === 'string' && r.length === rows[0].length);
    if (ok) thumb = { grid: rows, map: meta.thumb.map };
    else console.warn(`  ! ${game}/game.json thumb has ragged rows — ignoring`);
  }
  return {
    name: game,
    title: (meta.title && String(meta.title).trim()) || titleOf(game),
    description: (meta.description && String(meta.description).trim()) || '',
    tags: Array.isArray(meta.tags) ? meta.tags.map(String).slice(0, 4) : [],
    thumb,
  };
}

// ── 1. Build each game ─────────────────────────────────────────────────────────
for (const game of games) {
  const base = `${BASE}${game}/`;
  console.log(`\n▶ Building ${game}  (base ${base}) ...`);
  // Base via env (GAME_BASE), NOT a CLI flag (Git Bash mangles a leading "/").
  execSync(`npx vite build --config games/${game}/vite.config.mjs games/${game}`, {
    stdio: 'inherit',
    env: { ...process.env, GAME_BASE: base },
  });
}

// ── 2. Build the model + copy committed covers (optional) ──────────────────────
const model = games.map((game) => {
  const m = metaOf(game);
  const srcCover = join(gamesDir, game, 'cover.png');
  if (existsSync(srcCover)) {
    copyFileSync(srcCover, join('dist', game, 'cover.png'));
  }
  return { ...m, href: `${BASE}${game}/` };
});

// ── 3. Write the hub manifest (typed TS the hub imports) ───────────────────────
const manifest = `// GENERATED by scripts/build-all.mjs — do not edit by hand.
import type { PixelGrid } from '../../src/pixel';

export interface HubGame {
  name: string;
  title: string;
  description: string;
  tags: string[];
  href: string;
  thumb: PixelGrid | null;
}

export const GAMES: HubGame[] = ${JSON.stringify(
  model.map(({ name, title, description, tags, href, thumb }) => ({
    name,
    title,
    description,
    tags,
    href,
    thumb,
  })),
  null,
  2,
)};
`;
writeFileSync('hub/src/games.generated.ts', manifest);

// ── 4. Build the hub LAST (emptyOutDir:false keeps dist/<game>/) ───────────────
console.log(`\n▶ Building hub  (base ${BASE}) ...`);
execSync('npx vite build --config hub/vite.config.mjs hub', {
  stdio: 'inherit',
  env: { ...process.env, HUB_BASE: BASE },
});

// ── 5. Inject crawlable fallback links into the built hub index.html ───────────
const links = model
  .map(
    (g) =>
      `<li><a href="${escapeHtml(g.href)}">${escapeHtml(g.title)}${
        g.description ? ' — ' + escapeHtml(g.description) : ''
      }</a></li>`,
  )
  .join('\n        ');
const hubIndex = 'dist/index.html';
let html = readFileSync(hubIndex, 'utf8');
html = html
  .replace('<!--GAME_LINKS-->', links)
  .replace('<!--GAME_LINKS_NOSCRIPT-->', links);
writeFileSync(hubIndex, html);

// .nojekyll skips Jekyll processing on GitHub Pages.
writeFileSync('dist/.nojekyll', '');

console.log(`\n✓ Built ${games.length} game(s) + Phaser hub → dist/ (base ${BASE})`);
